### ISSUE TITLE
Release pcl_msgs to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/pcl_msgs#14]
Would you mind releasing `pcl_msgs` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 64 repos need it.

I'm not sure how much work it will need. At a minimum it needs #13.

**Comment by SteveMacenski** [comment]
I can take care of that tomorrow.

**Comment by SteveMacenski** [comment]
Done -- sorry my todo list app mistook "next monday" for the monday after next. 

https://github.com/ros/rosdistro/pull/24099
