### ISSUE TITLE
Building PCL from source

### ISSUE THREAD

**Issue by Bannigo** [ros-perception/pcl_msgs#16]
Hello,
         I was planning to build the pcl_perception packages from the source since I want to use PCL-1.11.1. While building them, I first tried to pcl_msgs via cmake.., make -j8, and sudo make install. But still it is not able to find the package-:

Could not find a package configuration file provided by "pcl_msgs" with any
  of the following names:

    pcl_msgsConfig.cmake
    pcl_msgs-config.cmake

How to proceed?

**Comment by SteveMacenski** [comment]
Please ask on ROS answers
