### ISSUE TITLE
Galactic / Rolling release has unkown upstream?

### ISSUE THREAD

**Issue by paulerikf** [ros-perception/pcl_msgs#17]
I've run into an issue where `rosinstall_generator --upstream --rosdistro <galactic/rolling> pcl_msgs` fails with 
```
The following repositories with an unknown upstream will be ignored: pcl_msgs
```

Works fine with `--rosdistro foxy` though.

Notably the rosdistro distribution.yaml file for galactic is missing a `source` section
https://github.com/ros/rosdistro/blob/ef95fc09c24aa52fec8946f606dc55eae155416b/galactic/distribution.yaml#L2468

It's present in the foxy one
https://github.com/ros/rosdistro/blob/ef95fc09c24aa52fec8946f606dc55eae155416b/foxy/distribution.yaml#L2904

I don't quite have a handle on ros package releases, so unsure of why the source section disappeared. Any ideas why? Is this fixable?

**Comment by SteveMacenski** [comment]
Huh that is odd. I don't think that is intention. I'm not actually seeing a release on this repo run so I'm not 100% sure who did that release or how exactly that was setup. 

It looks like it was pulled in from Rolling's file when Galactic was bootstrapped https://github.com/ros/rosdistro/blob/ef95fc09c24aa52fec8946f606dc55eae155416b/rolling/distribution.yaml#L2316 but I'm not sure who did that or why we don't have a release tag in this project for it.

**Comment by SteveMacenski** [comment]
Oh I see @paulbovbel did this and he released as a tag not a release block. Also a perfectly suitable way to handle it.

**Comment by paulerikf** [comment]
Ah, I see.  Forgive my ignorance, can we just manually add the source section (not sure what the doc section does, but maybe that too I guess?) to the rolling and galactic distribution.yaml files on rosdistro? Or are they autogenerated from something in the release process?

**Comment by SteveMacenski** [comment]
I believe so - they are autogenerated from a process but if you carefully write it up, it should be fine

**Comment by paulerikf** [comment]
Issue resolved! [Rosdistro PR](https://github.com/ros/rosdistro/pull/32322#) merged, running `rosinstall_generator --upstream --rosdistro <galactic/rolling> pcl_msgs` now works! 
Thanks for the help :)
