### ISSUE TITLE
Ros2 Windows Support

### ISSUE THREAD

**Issue by Dashenboy** [ros-perception/pcl_msgs#19]
Hello Im trying to get the pcl conversion tool on windows but in order for me to do that i have to build this https://github.com/ros-perception/perception_pcl. When building it cannot find PCL_msgs. it says 
**
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "Findpcl_msgs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pcl_msgs",
  but CMake did not find one.

  Could not find a package configuration file provided by "pcl_msgs" with any
  of the following names:

    pcl_msgsConfig.cmake
    pcl_msgs-config.cmake

  Add the installation prefix of "pcl_msgs" to CMAKE_PREFIX_PATH or set
  "pcl_msgs_DIR" to a directory containing one of the above files.  If
  "pcl_msgs" provides a separate development package or SDK, be sure it has
  been installed.

---
Failed   <<< pcl_conversions [3.17s, exited with code 1]

Summary: 0 packages finished [3.38s]
  1 package failed: pcl_conversions
  1 package had stderr output: pcl_conversions
  2 packages not processed
**

So when i do try to build this repo of pcl_msgs i get this error,
**
--- stderr: pcl_msgs
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.

---
Failed   <<< pcl_msgs [6.17s, exited with code 1]

Summary: 0 packages finished [6.41s]
  1 package failed: pcl_msgs
  1 package had stderr output: pcl_msgs
  3 packages not processed
**

Do you have any clue what is going on, as far as im know ros2 doesnt use catkin??

**Comment by SteveMacenski** [comment]
Ask or search on Robotics Stack Exchange, this is a basic installation issue that you should be able to find with a google search

**Comment by Dashenboy** [comment]
Sorry, i don't mean to come off as a douche but ros2 doesn't use catkin anymore. My source is this link.

https://github.com/colcon/colcon-core/issues/302
https://answers.ros.org/question/385797/issue-with-creating-a-workspace-ros2/ 

2 anecdotal pieces of evidence.

**Comment by Dashenboy** [comment]
I cloned the wrong repo! Thank you!
