### ISSUE TITLE
Fuerte Branch

### ISSUE THREAD

**Issue by MarkusEich** [ros-perception/pcl_msgs#2]
I created a quick fuerte branch for convenience. If there would be a fuerte branch in the repo, I could create a pull request.

**Comment by mintar** [comment]
+1 to this. Could somebody please push the `fuerte-devel` branch of https://github.com/MarkusEich/pcl_msgs into this repository? I just tested it (it works), and it's required to get PCL 1.7 running properly on fuerte.

**Comment by tfoote** [comment]
pushed
