### ISSUE TITLE
pcl_msgs in groovy place messages in the pcl namespace

### ISSUE THREAD

**Issue by trainman419** [ros-perception/pcl_msgs#3]
From looking at the version of pcl_msgs that is released into Groovy, it looks like the messages are placed into the PCL namespace; probably for compatibility with older versions of PCL.

Unfortunately, this isn't the API that users expect, and it's inconsistent with Hydro: http://answers.ros.org/question/137031/not-able-to-compile-a-msg-using-pcl_msgs-type-variables

Is it possible to release a version of pcl_msgs into Groovy that installs the PCL messages into both locations on Groovy?

**Comment by paulbovbel** [comment]
Implemented with 4217eeb2dc8bfe59365a40e9ec520c920f587eef, released as 0.04 for groovy only.
