### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by jackieokay** [ros-perception/pcl_msgs#6]
@paulbovbel It would be great to get pcl_msgs, pcl_conversions and perception_pcl into Kinetic ASAP, since it blocks a few packages in the desktop-full tree. Let me know if I can be of assistance.

**Comment by paulbovbel** [comment]
Hi @jacquelinekay, i will definitely be able to get it done Wednesday next week, but no sooner, apologies.

**Comment by jackieokay** [comment]
That's ok. Is it alright with you if we run a bloom-release sooner (probably tomorrow) or are there items that you want to address before the initial Kinetic release?

**Comment by jackieokay** [comment]
Thanks!
