### ISSUE TITLE
Release pcl_msgs into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-perception/pcl_msgs#8]
This is a friendly reminder that the Melodic buildfarm is [now available](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248). It would be great to have a release of `pcl_msgs` into Melodic, as it is currently directly blocking 2 packages and indirectly blocking 13 packages (http://repositories.ros.org/status_page/blocked_releases_melodic.html). Thank you!

**Comment by paulbovbel** [comment]
done!

**Comment by clalancette** [comment]
Thank you!
